application: idiomatic-fu
version: 1
runtime: python
api_version: 1

handlers:
- url: /(robots.txt|favicon.ico)
  static_files: static/\1

- url: /google7db36eb2cc527940.html
  static_files: static/robots.txt

- url: /css
  static_dir: css

- url: /static
  static_dir: static

- url: /js
  static_dir: js

- url: /test.*
  script: gaeunit.py

- url: .*
  script: main.py


